### ISSUE TITLE
Add something like `git stree install-hooks`

### ISSUE THREAD

**Issue by lsmag** [deliciousinsights/git-stree#12]
I believe it's useful having a pre-commit hook that prevents commits mixing code from different repos. Also, if a commit has strictly subrepo patches, a post-commit hook can add `[stree name]` before the commit message.

So `git stree install-hooks` installs these two hooks to avoid "broken" commits. What do you think?

**Comment by tdd** [comment]
Hey!

It's an interesting idea. Maybe not a 100%-forbidding hook, but at least a prompting one ("looks like you're committing changes to multiple subtrees at once, are you sure you don't want to split? [yN]"), if a TTY is active.

Keeping this open.
