### ISSUE TITLE
stree push to different new branch (pull request workflow)

### ISSUE THREAD

**Issue by pedroteixeira** [deliciousinsights/git-stree#14]
Hi, do you have any suggest for a way to push a subtree to the remote to another branch?

for example: initially, a subtree was pulled from master, but it seems common to push it to the remote to another branch for a pull request. Any recommended workflow for this case? It seems I would have to change de current config for the dir, right?

thanks.

**Comment by tdd** [comment]
Hey,

Well, if you PR from a fork to the upstream repo, it doesn't matter that you're on `master` in your fork. Agreed, a dedicated branch would be more descriptive, but it's not *required*.

If you're working with upstream directly, then def another branch. I'm not sure what the best way to let you specify this with `stree` is.  Perhaps an extra, optional param in `git stree add` plus an extra, upstream-changing command in `git stree` (say, `git stree set-upstream`) so you can change the upstream branch you pull from / push to (once you start pushing to a branch, you'd pull from that too, in an ongoing-PR scenario).

**Comment by pedroteixeira** [comment]
Perhaps both `stree pull and push` could accept an optional argument for the 'remote branch' to be used (diffeferent from the current/default config)?

**Comment by pedroteixeira** [comment]
I tried to just change the `branch` in git/.config but I got the following when trying to 'stree push'

```
fatal: Cannot update paths and switch to branch 'stree-backports-my-stree-name' at the same time.
Did you intend to checkout 'stree-name/feature/x' which can not be resolved as commit?
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
```

**Comment by tdd** [comment]
Hey Pedro,

Clearly hacking the config won't do, as the backport branch's upstream is defined already and my code probably assumes so. You'd probably need to manually adjust the backport's branch upstream using `git branch --set-upstream-to=…` for that. This also assumes the remote branch you're using **exists** (as it will try to pull from it first).

**Comment by lsmag** [comment]
Maybe something like `git stree push <name> [-b branch] [<commit>...]`, as it won't break the existing cmd interface, just extend it.

There's already some metadata regarding the upstream's last synced branch so maybe we can also add some sort of tty (if available) to confirm the action.
