### ISSUE TITLE
`brew test git-stree` fails with git-stree 0.4.5

### ISSUE THREAD

**Issue by jawshooah** [deliciousinsights/git-stree#19]
I've submitted a PR to update the Homebrew formula from 0.4.0 to 0.4.5 (Homebrew/homebrew#39992), but the build is breaking because `brew test git-stree` no longer works.

Here's the [log](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26557/version=yosemite/testReport/brew-test-bot/yosemite/test_git_stree/) for the failed build. Any idea what's going wrong?

**Comment by tdd** [comment]
Hey Josh,

Sorry about this; there was actually a bug introduced in my latest code for `add`. I fixed it and force-pushed the tag (yes, I know… Couldn't bring myself to releasing a fresh 0.4.6 with yet again the full details).

Can you retry?

Also, we need to get in touch on streamlining the Homebrew part; I'm not familiar with how this works, but I'd love to get involved and be able to take care of / automate Homebrew updates when this repo creates releases.

**Comment by jawshooah** [comment]
No problem, just pushed again and it seems to be working.

You likely could automate the process, as the only changes required are updating the `url` and `sha256` stanzas, which should be easy enough to script.
