### ISSUE TITLE
Provide support for `.gitstrees`

### ISSUE THREAD

**Issue by tdd** [deliciousinsights/git-stree#3]
Every command should update, stage and commit (if need be) a `.gitstrees` file at the root of the WD, to ease sharing of stree config.

A `git stree sync` command should sync its data into the local config (checking for timestamps to remain efficient though, unless `-f`).

Every operational command besides should start by internally doing a `git stree sync` (no `-f`) to auto-sync if need be, especially for strees introduced by collabs that we start working with.

**Comment by lsmag** [comment]
I'm looking forward for this feature. If you don't mind I can develop something (I already forked the repo to get the `install-hooks` done).

**Comment by tdd** [comment]
Feel free to get the ball rolling: that's open-source! I can't guarantee I'll merge it *as-is*, but a starting point is always good!

**Comment by gvt** [comment]
+1 for this. I came here to upvote the `.gitsubtrees` file mentioned in tdd's blog post but this seems like the evolution of that.

**Comment by tdd** [comment]
Yes it is.

**Comment by jpwarren00** [comment]
Would you like some help with this?

**Comment by tdd** [comment]
Hey John,

Thanks for pitching in!

I have no great visibility into the roadmap until I get around to fixing 
the core issue at the heart of many reported issues already.  When I 
finally do some housecleaning in here (sorry it takes so long…) I can 
start assessing features properly and possibly dispatching the work.

It would need a prior clean CONTRIBUTING.md guide, though.  And most of 
all, it would need *good test coverage* before, to ensure PRs don't 
introduce any breakage.

Best,

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by tdd** [comment]
Closing as this gets moved to our `TODO.md` roadmap.
