### ISSUE TITLE
STree won't work after cloning

### ISSUE THREAD

**Issue by rogopag** [deliciousinsights/git-stree#35]
Maybe this is a misunderstanding on my side, but after setting up the subtrees for a particular project and pushing the change to the remote, if someone else is cloning the repo to its local, subtree won't be configured properly.

All the subtree files will be in place but using STree commands will result in something like:

- git stree list -v 
  "no output"

- git stree pull NAME

✖ STree 'toolset-common' does not seem (fully) defined: missing 'remote.stree-toolset-common.url' configuration.

- git stree rm NAME
  git push origin master
 git stree add NAME -P prefix URL

error: Entry 'embedded/common/WPML/wpml-string-shortcode.php' overlaps with 'embedded/common/WPML/wpml-string-shortcode.php'.  Cannot bind.

To workaround these issues we ended up editing ".git/config" manually in every local adding the subtrees informations needed to make things work?

Something like:

[branch "develop"]
	remote = origin
	merge = refs/heads/develop
[remote "stree-toolset-common"]
	url = git@git.onthegosystems.com:toolset/toolset-common.git
	fetch = +refs/heads/master:refs/remotes/stree-toolset-common/master
[stree "toolset-common"]
	prefix = toolset-common
	branch = master
	latest-sync = 4ce50b6
[remote "stree-onthego-resources"]
	url = git@git.onthegosystems.com:toolset/onthego-resources.git
	fetch = +refs/heads/master:refs/remotes/stree-onthego-resources/master
[stree "onthego-resources"]
	prefix = onthego-resources
	branch = master
	latest-sync = 05f7a36

Is there are alternative and more elegant way to achieve this? Is that correct that stree needs configuration for every different repository instance.

Is there a  way to use stree commands to set the configuration when subtree files are already in place, without getting the overlap error?

Thanks in advace,
Riccardo

**Comment by csemrau** [comment]
Hi Riccardo!

Currently stree does not support checked-in configuration. A feature request for this can be found as https://github.com/tdd/git-stree/issues/3

You do understand that only a developer who manages the subrepository (via pull or push) needs this? Any other developer who just uses the files from the subrepo does not need stree, and can act on the subrepo files like for any other file from the local repository.

Regards,
Christian Semrau

**Comment by garywu** [comment]
So what is the recommended procedure for a developer who manages the subrepository? 
git stree add doesn't work if the subrepo's files are already in place. So how does one setup the container repo correctly after the first time? Is manually modifying the config the only way?

**Comment by tdd** [comment]
Right now, it is. We'll be working on making `add` play nicer with existing stree files in the future.

**Comment by garywu** [comment]
There is actually another way. Delete the folder for the subrepository and then git push. Then just add it back in with stree like in the first place.

**Comment by johnhut** [comment]
You get similar symptoms if you delete a subtree but later git reset --hard back to when the subtree still existed.  As already mentioned issue #3 should solve this.

**Comment by ptcuops** [comment]
I'm new to subtrees and stree in particular, but this confuses me a bit. I've made changes in my actual repo that other repos use as a subtree. What is the proper procedure to get those changes to the "container" repos? As mentioned int he original post here, "git stree pull my_subtree" doesn't work if the environment I'm in is not the original development environment where the subtree was added.

**Comment by tdd** [comment]
Hey there,

So the workflow would go as follows:

1) Push the changes from your subtree-only maintenance repo (the one you 
say you made changes to)

2) Have 1 of the people with the stree configured in their container 
repo do a git stree pull on it, then push that.

3) Anyone else can then pull their container repo to get these updates.

And yes, once we get some form of .gitstrees support file, anyone will 
be able to stree pull without further config.

Best,

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by samuelmartineau** [comment]
Hi,

I face an identical problem due to a migration of the stree configured workstation. 
Like Riccardo, it's probably a misunderstanding on my side, but Is there a way to do that? (other than copying the git config file)

Otherwise, very nice to use up to now :thumbsup:

**Comment by tdd** [comment]
I'm afraid right now you'd have to copy the relevant remote/stree items 
of your .git/config from a configured repo to the new one.  Sorry about 
that!

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by samuelmartineau** [comment]
No problem @tdd,

It works after the copy and I hope this new one is set up for a long time :wink:
Thks

**Comment by tdd** [comment]
Closing this in as a dup of #3.
