### ISSUE TITLE
'git stree pull' deletes nested stree

### ISSUE THREAD

**Issue by ecraven** [deliciousinsights/git-stree#38]
Hello :)

Something I've just run into.
On a new repo (only one initial commit), if I run
````
git stree add core -P core /path/to/repo core-branch
git stree add plugin -P core/plugin /path/to/repo plugin-branch
````
I nicely see the nested code. Then, if I run 
````
git stree pull core
````
that deletes all the plugin files. How do I correctly handle nested strees?

**Comment by tdd** [comment]
Hey there,

I'm not quite sure this can be done. We rely on internal Git subtree-related mechanics, and I'm not confident these will properly preserve nested stree on pulls. We have ongoing issues trying to prevent pulls from overwriting any local work, and this may get solved along when we figure that general issue out.

Best,

**Comment by tdd** [comment]
Clearly nested subtrees won't work with Git. We can provide checks on add to avoid this. Closing this.
