### ISSUE TITLE
git stree add from inside a submodule infinite loop

### ISSUE THREAD

**Issue by conrado** [deliciousinsights/git-stree#41]
There's a corner-case, of when adding a subtree in an already configured submodule.

In such case the `normalize_prefix` function will go into infinite loop here:

https://github.com/tdd/git-stree/blob/c0fbce373d9f1150309d0f13df994da7909a3bee/git-stree#L343

You might ask, why would one mix these two different methods up? My reason is to immediately stop using submodules in order to later start refactoring out their use.

**Comment by tdd** [comment]
Hey,

So to turn a submodule into an stree/subtree you'd need to work at parent/container repo level anyway, not in the submodule's nested repo. I'm slating work on this for the 1.0 milestone, with:

* A pre-add check that detects you're in a submodule's nested repo, and tells you what the proper procedure is.
* A dedicated procedure/subcommand in the parent repo. Perhaps even working on the whole submodule list.
