### ISSUE TITLE
Subtree Central Repo branch name

### ISSUE THREAD

**Issue by dhuantes** [deliciousinsights/git-stree#43]
We have a number of reuse libraries that we previously used submodules for.  We started to move towards subtrees using git-subtree subcommand until another colleague recently suggested investigating stree.  We are glad he did as it is already saving me time.  Question I have is how many others have a simliar situation where a given library is used in multiple stree projects.  With subtree's I was using an approach that created a branch in each repo for each subtree and was considering doing the same with stree's (i.e. stree-BigProject).  This way each project could comfortably push back to the central repo without fear of breaking someone else's build.  How do others do this?  Suggestions?  Thanks!

**Comment by tdd** [comment]
Are you saying each (or any) **subtree repo** has a **branch per container project using it**?!

if so, then it feels like **way** too much coupling, and quite likely, as the code varies so much from one repo to the other, it shouldn't even be centralized to begin with…

If you keep going with this, I would assume the branches are because submodules and `git subtree` **wouldn't let you choose which commits-in-container to push** back to the core subtree repo, is that correct?

This shouldn't be an issue anymore as `git stree` **lets you specify which commits to push back**, so if you are hygienic about it (trying to separate the commits that do generic stuff in the stree vs. the commits that do container-specific stuff), you shouldn't need these kinds of branches.

Best,

**Comment by dhuantes** [comment]
That was my thinking (i.e. waaay to much coupling).  With submodules we actually had the repository residing in the superproject so commiting changes to the central repository was just like dealing with the standalone repository.  Because of this individual developers were a bit more conscientious about what they pushed back to the central repository. But when they did they would specify a branch like 'Fix-DivisionByZero' or 'Feature-XMLSupport' and would merge it into the main development branch with the --no-ff option so that new changes and their purpose were highlighted in the  gitk tree for other users of these codes.  I think 2 things happened with subtree introduction to the team.  The diligence of isolating commits was no longer enforced (i.e. submodules) so developers were less conscientious about changes to these reuse libraries.  Which with subtrees is problematic because, as you say, it pushes back all commits to the subtree which subsequently requires cherry-picking on the central repo side to not break the main development branch.  stree's ability to select which commits is a step in the right direction.  The only thing we lose from our previous submodule workflow is the ability to create a branch so that the change is more obvious to other users of the central repo.  Of course the details are there but the gitk visualization of --no-ff merged branches is nice.  I do like the fact that stree  persists/remembers all the information for the subtree repository so that 'git stree push <name>' just works but what would be nice would be a feature that allows the user to 'git stree push <name> [branch]' that would create branch  in central repo off of the current tracking branch.  This does open a can of worms but would support our workflow.  Or we just give up on our pretty gitk tree and make sure each commit comment starts with 'Fix:' or 'Feature:'....  Might just be the approach to take for now.  Thanks!

**Comment by tdd** [comment]
Hey there,

As for your branch-per-push wish, if the only goal is to see the perimeter of your changes in the log, you don't even need a remote branch for that: `git stree push` could just create the branch locally off an up-to-date tracking backport, then merge `--no-ff` it locally, and push.  Could be something we add at some point.

Best,
