### ISSUE TITLE
Converting from git-subtree to git-stree

### ISSUE THREAD

**Issue by dhuantes** [deliciousinsights/git-stree#44]
Is there a straight forward way to convert a git-subtree project to a git-stree project?  I have a subtree project that was created awhile ago for a colleague who never did any upstream pushes.  The approach i was going to take was:

1. Create a new git-stree project using the last synchronize commits from his of the subtree repositories
2. Diff the two repositories (i.e. old subtree and new git-stree) recursively and pull in all the changes.
3. Go through each commit and determine which ones are good candidates for upstream pushes 

The primary reason for doing this is because I have 3rd project that will use a lot of these same libraries and I want to make sure to capture the bug fixes and other enhancements from the subtree project that has never pushed upstream. Thoughts?  Suggestions?  I realize that the new stree project will lack the detailed history that the older subtree project has but not sure this is another way.  Thanks!

**Comment by tdd** [comment]
Hey,

Clearly for this you'll need a manual approach, quite like the one you're describing.

It might work to just bring in the proper stree configuration, right in the current container project, and then for each subtree log -p or something, filtering on the subtree's directory and starting from the latest sync point, to finally do a commit-specifying git stree push on it.  This would let you leverage git's builtin diffs instead of manually recurse-diffing between two WDs.

**Comment by dhuantes** [comment]
Ok... I tried something....

1. Created a new subtree container project to replace the older subtree project.  It is not complete just added the first stree
2. I copied the .git/config entries from the new stree container project to the old subtree project.  I attempted to push and after receiving and error and looking at gitk realized this wouldn't work because the stree-<project>/<branch_name> did not exist. <scratched head>
3. I then created a dummy test branch on the old subtree project and then executed a 'git stree pull <stree project name>'.  This successfully created the stree-<project>/<branch_name> branch and stree structure that was visible in gitk
4. I then proceeded to try to do a commit specific git stree push <SHA1> that worked...

I'll let you know if I run into any issues as I proceed... Thanks!

**Comment by dhuantes** [comment]
### Resolving conflicts that occur with 'git stree push  \<stree-name\>'
My second stree was not quite as successful... Here is the sequence of events
* **1**. Found the most recent common commit between stree that I was adding and the subtree project I wanted to push commits from (fortunately only 1 commit apart)
* **2**. Perfomed 'git stree add <new-stree> -P <new-stree> server@repos-path <branch> on the new stree container (recall this is the new stree container project that is going to replace old subtree project)
* **3**. Compared .git/config from old subtree and new stree container project and moved copied entries for new stree over to old subtree .git/config file
* **4**. Executed a 'git stree list' to make sure all was correct.  The new stree was listed as expected
* **5**. Created a temporary branch (i.e. will be deleted later) and performed a 'git stree pull \<new-stree-name\>' in order to pull in the new stree's commits. 
* **6**. Checkout branch in old subtree project I started on and then deleted the temp branch created in step 5.
* **7**. There were multiple commits between the time that the subtree was added to the old container and now but there was actually only one commit that change the subtree that dealt with the new stree I had just configured/created.  So I performed a 'git stree push \<new-stree-name\> \<commit\>'.  Unfortunately there were conflicts and I got the following error: 
```
error: could not apply 6873634... - Added UNICODE_BUILD Option and turned it
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
?? Could not cherry-pick 6873634 - Added UNICODE_BUILD Option and turned it on by default. - Added conditional that checks if the
UNICODE_BUILD option is ON and provides the appropriate preprocessor defines if it is.
```
* **QUESTION**: After this I'm left on the stree-backports-<new-repo-name> in CHERRY-PICKING state.   What is the correct sequence of steps to resolve the conflict and the commit both locally and on the remote stree so that the push is completed?  Thanks!

**Comment by dhuantes** [comment]
### Resolution

I skimmed the git-stree code and saw that the conflict kept me only a few commands away from completing the push.

So... I went head did the following

#### Resolved Commit
```
git mergetool   
```
**NOTE**: in my environment I use WinMerge to do a side by side comparison of conflicts to help me resolve them.  If one of the files being compared has a change made and saved WinMerge will assume that file has the correct state and will stage it for commit.  

#### Commited Staged/Resolved Changes
```
git commit -m "resolved commit" 
```
**NOTE**: commit has multiple options at the command line.  This is just one option...

#### Completed push to stree remote as git-stree would have done if conflict had not occurred
```
git push stree-<stree-name> stree-backports-<stree-name>:<branch>
```
**NOTE**: the \<branch\> name in the above command is the branch name you chose to add the stree with. If you can't remember just execute the list command as shown below and the string following the @ character at the end of your stree remote is that branch name.  Also since you've already attempted an stree push there git stree list will also provide you the branch name being used for backports with a message like '(backports through stree-backports-\<stree-name\>)'
```
git stree list
```
