### ISSUE TITLE
Not working for pull - when files are changed

### ISSUE THREAD

**Issue by BobTB** [deliciousinsights/git-stree#45]
I made a simple test, two remote repositories (dev, lib). Clone dev, git stree lib in the dev subfolder. 
git stree push works as expected. 

If I edit a file in cloned lib outside of dev stree, add and commit and then do the git stree pull lib in the dev I get the merge conflict in this edited file. Everytime. 

This is sadly useless for any edits made upstream in the library. I thought that this will solve all my problems as it looked very promising. Sadly it does not work at all, every edit in the original lib is conflicting with the untouched files in the imported stree... :(

It works the other way around, but mostly I will need the library updates pulled... which is completely broken.

Can anyone use this at all?

**Comment by tdd** [comment]
Hey Bob,

This is very weird.  There *are* some use-cases that don't work, as in #39, and we're investigating this very soon (so sorry we're submerged for now), but it's been working quite well in similar scenarios on a number of codebases. Simple pulls of updated stree remotes on untouched local stree codebase works for a lot of people. I'm quite puzzled as to what the failure conditions are.

We're going to change the underlying mechanism anyway, to fix other, unrelated issues. Chances are the new mechanism will remove that elusive failure condition anyway.

Sorry this doesn't cut the mustard for you. I hope we can fix this over the holidays.

**Comment by BobTB** [comment]
Yes, now that I look at it, this is almost the same as #39. Hope you will get this fixed, as this stree is otherwise a very nice idea!

**Comment by tdd** [comment]
Marking this as a clear dup of #39 (which in turn relates to #22).
