### ISSUE TITLE
manage strees on multiple locations

### ISSUE THREAD

**Issue by stefanlendl** [deliciousinsights/git-stree#47]
I added strees to my dotfile repos.
When I check out the repo on another location the source of the plugin is pulled as well but no information about the stree.

I updated my local copy of git-stree so i can pass --no-fetch to the add command so only the remote and the git config is set but not the whole repo pulled in.

A feature like this will be implemented with the sync command, do I see that right?
.gitstree containing simply <name> <prefix> <url>

When adding that please make sure to not add it in the repo root!
When using it for dotfiles, the root for all repos is $HOME and then multiple .gitstree would conflict
This is the main reason git submodules can't be used with multiple dotfile repos in $HOME

**Comment by tdd** [comment]
Hey Orsonn,

Yes, if you're looking at existing issues you'll see this has already
been discussed.

You'll also see we're investigating depreciating strees in favor of
the git-subrepo contrib tool, which goes further (and supports your
use case).

Best,


On Mon, Jan 11, 2016, at 17:53, orrsonn wrote:
> I added strees to my dotfile repos
>
When I check out the repo on another location the source of the plugin
is pulled as well but no information about the stree


> I updated my local copy of git-stree so i can pass --no-fetch to the
> add command so only the remote and the git config is set but not the
> whole repo pulled in


> A feature like this will be implemented with the sync command, do I
> see that right?
>
gitstree containing simply


> When adding that please make sure to not add it in the repo root!
>
When using it for dotfiles, the root for all repos is $HOME and then
multiple gitstree would conflict
>
This is the main reason git submodules can't be used with multiple
dotfile repos in $HOME


> — Reply to this email directly or view it on GitHub[1].


>

--
Christophe Porteneuve
tdd@tddsworld.com
 


Links:

  1. https://github.com/deliciousinsights/git-stree/issues/47
